---

- name: ensure epel is installed
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  register: install_epel
  until: '"error" not in install_epel'
  retries: 5
  delay: 10
  when: ansible_distribution == 'CentOS'

# rhevm-guest-agent-common package is not yet available for RHEL 8
- name: ensure ovirt guest agent package is installed
  package:
    name: "{{ ovirt_guest_agent_package_name[ansible_distribution] }}"
  register: ovirt_package_installation
  when: ansible_distribution_major_version|int < 8

# try installing qemu package on RHEL/CentOS 8 for now
- name: ensure qemu guest agent package is installed
  package:
    name: qemu-guest-agent-common
  when: ansible_distribution_major_version|int == 8
  register: ovirt_package_installation
  ignore_errors: yes

- name: ensure ovirt guest agent is enabled
  service:
    name: "{{ ovirt_guest_agent_service_name }}"
    enabled: yes
  when:
    - ansible_distribution_major_version|int < 8
    - ovirt_package_installation is succeeded

- name: ensure qemu guest agent is enabled
  service:
    name: "{{ qemu_guest_agent_service_name }}"
    enabled: yes
  when:
    - ansible_distribution_major_version|int == 8
    - ovirt_package_installation is succeeded