---

- name: Ensure SELinux is set to proper state
  selinux:
    policy: "{{ selinux_policy_name }}"
    state: "{{ selinux_state }}"
  register: selinux_set_state

- name: Reboot if required
  reboot:
  when: selinux_set_state.reboot_required