---

- name: run getenforce
  command: getenforce
  register: getenforce_command

- debug:
    msg: "{{ getenforce_command.stdout }}"
  when: getenforce_command.stdout is defined

- name: Ensure SELinux is set to proper state
  selinux:
    policy: "{{ selinux_policy_name }}"
    state: "{{ selinux_state }}"
  register: selinux_set_state

- name: Reboot if required
  reboot:
  when: selinux_set_state.reboot_required