---
- name: Add VMWare tools repository.
  template:
    src: vmware-tools.repo.j2
    dest: /etc/yum.repos.d/vmware-tools.repo

- name: Import VMWare tools GPG keys.
  rpm_key:
    key: "https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub"
    state: present

- name: Create temporary directories for VMware tools.
  file:
    path: "/tmp/{{ item }}"
    state: directory
  loop:
    - vmfusion
    - vmfusion-archive

- command: ls -lah /home/{{ local_account_username }}
  register: vaglist

- debug:
    var: vaglist

- name: Mount VMware tools.
  mount:
    name: /tmp/vmfusion
    src: /home/{{ local_account_username }}/linux.iso
    fstype: iso9660
    opts: loop
    state: mounted

- name: Decompress VMware Tools installer into archive folder.
  shell: tar xzf /tmp/vmfusion/VMwareTools-*.tar.gz -C /tmp/vmfusion-archive

- name: Run the VMware tools installer.
  shell: /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default

- name: Unmount VMware tools.
  mount:
    name: /tmp/vmfusion
    src: /home/{{ local_account_username }}/linux.iso
    fstype: iso9660
    state: absent

- name: Remove temporary directories for VMware tools.
  file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - vmfusion
    - vmfusion-archive

- name: Delete VMware Tools.
  file:
    path: /home/{{ local_account_username }}/linux.iso
    state: absent
